<?php

/**
 * @Author SeanJA <http://seanja.com>
 * @license MIT
 */
module_load_include('inc', 'smush_it', 'smush_it.class');

/**
 * Get the document root for the current Drupal installation.
 * $_SERVER['DOCUMENT_ROOT'] is not reliable across all
 * systems, so we need a way to get the correct value.
 * @staticvar string $root The value that will be returned
 * @return string
 */
function _document_root() {
  static $root;
  if (!$root) {
    $absolute_dir = dirname(__FILE__);
    $relative_dir = drupal_get_path('module', 'smush_it');
    $root = substr($absolute_dir, 0, -1 * (1 + strlen($relative_dir)));
  }
  return $root;
}

/**
 * Push an image through the smush.it api
 * @global string $base_url
 * @staticvar SmushIt $s The smush.it object
 * @staticvar bool $smush_it_testing Whether or not we are in test mode
 * @staticvar string $smush_it_test_image The image that will be used in test mode
 * @param file $file The file being processed
 */
function _smush_image(&$file) {
  global $base_url;
  static $s, $smush_it_testing, $smush_it_test_image;
  if (!$s) {
    $s = new SmushIt();
    $smush_it_testing = variable_get('_smush_it_testing', 0);
    $smush_it_test_image = variable_get('_smush_it_test_image', null);
  }
  $filepath = $file['filepath'];

  if (!$smush_it_testing) {
    //use the actual file
    $file_url = $base_url . DIRECTORY_SEPARATOR . $filepath;
  } else {
    //use a web accessible file set in the settings section
    $file_url = $smush_it_test_image;
  }
  try {
    $q = db_query('SELECT smushid FROM {smush_it} WHERE fid = %d', $file['fid']);
    $exists = db_fetch_array($q);
    if(!empty($exists['smushid'])){
      throw new Smush_exception('The file has already been smushed', null);
    }
    $smushed = $s->compress($file_url);
    $file = _save_smush_file($file, $smushed);
    //update the mimetype just incase something actually uses it
    list($width, $height, $type, $attr) = getimagesize($smushed->dest);
    $file['filemime'] = image_type_to_mime_type($type);

    //drupal_write_record expects an object, not an array
    $file_object = (object) $file;
    drupal_write_record('files', $file_object, array('fid'));
    //store the smushed info in the database as well so the image isn't processed over and over again
    $smush_it_object = (object) array(
        'fid' => $file['fid'],
        'space_saved' => $smushed->src_size - $smushed->dest_size
    );
    drupal_write_record('smush_it', $smush_it_object);
  } catch (Smush_exception $e) {
    //no savings means that the file is as small as it can be (not really an error, but returned as one by the api)
    if ($e->getMessage() == 'No savings') {
      //store the smushed info in the database as well so the image isn't processed over and over again
      $smush_it_object = (object) array(
          'fid' => $file['fid'],
          'space_saved' => 0
      );
      drupal_write_record('smush_it', $smush_it_object);
    } else {
      //An actual error! Send it to the user
      drupal_set_message($e->getMessage() . ' => ' . $file['filename'], 'error');
      return false;
    }
  }
  return true;
}

/**
 * Save the smushed file
 * @param file $file
 * @param smushed $smushed
 * @return file $file
 */
function _save_smush_file($file, &$smushed) {
  //@TODO: there has to be a better way to do this part...
  $root_path = _document_root() . '/';
  $remote = fopen($smushed->dest, "rb");
  $new_file = $root_path . $file['filepath'] . '.new';
  $original_file = $root_path . $file['filepath'];
  $old_file = $root_path . $file['filepath'] . '.old';
  //read the file in bit by bit
  $temp = fopen($new_file, 'w+');
  while (!feof($remote)) {
    fwrite($temp, fread($remote, 8192));
  }
  fclose($temp);
  fclose($remote);

  //backup the old file (.old) and replace it with the new file
  rename($original_file, $old_file);
  rename($new_file, $original_file);
  $file['filesize'] = $smushed->dest_size;
  return $file;
}

/**
 * Implements hook_nodeapi()
 * @staticvar string $image_mimes
 * @param node $node The node being manipulated
 * @param string $op The operation being performed
 * @param string $teaser
 */
function smush_it_nodeapi(&$node, $op, $teaser) {
  static $image_mimes;
  if (!$image_mimes) {
    $image_mimes = array('image/jpeg', 'image/png', 'image/gif');
  }
  $smush_on_create_update = variable_get('_smush_it_on_create_update', false);
  if ($smush_on_create_update) {
    switch ($op) {
      case 'insert':
      case 'update':
        if (user_access('upload files')) {
          foreach ($node->files as &$file) {
            if ($file['new'] && in_array($file['filemime'], $image_mimes)) {
              _smush_image($file);
            }
          }
        }
        break;
    }
  }
}

/**
 * Gets the information from the smush.it settings to run the cron job
 * if cron_count == 0 or cron_active == false then the cron job will not run
 * implementation of hook_cron()
 */
function smush_it_cron() {
  $cron_active = variable_get('_smush_it_cron_active', false);
  $cron_count = variable_get('_smush_it_cron_count', 0);
  if ($cron_active && $cron_count > 0) {
    _process_cron($cron_count);
  }
}

/**
 * Actually run the unprocessed images through smush.it
 * @param int $cron_count
 */
function _process_cron($cron_count) {
  //select the files where there is no equivalent smush_it entry
  $to_process = db_query('SELECT files.* FROM {files} 
    LEFT JOIN {smush_it} ON files.fid = smush_it.fid 
    WHERE smush_it.fid IS NULL 
    AND filemime IN (\'image/jpeg\', \'image/png\', \'image/gif\') 
    LIMIT 0 , %d', $cron_count);
  while ($image = db_fetch_array($to_process)) {
    _smush_image($image);
  }
}

/**
 * Add the smush.it settings menu item
 * implementation of hook_menu()
 * @return array 
 */
function smush_it_menu() {
  //smush it settings
  $items['admin/settings/smush-it'] = array(
    'title' => 'Smush.it',
    'description' => t('The settings for smush.it'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_smush_it_form_builder'),
    'access callback' => 'user_access',
    'access arguments' => array('administer upload'),
    'type' => MENU_NORMAL_ITEM,
  );
  
  //this seems redundant
  $items['admin/settings/smush-it/settings'] = $items['admin/settings/smush-it'];
  //replace values that are different for this menu item (it is a tab)
  $items['admin/settings/smush-it/settings']['type'] = MENU_DEFAULT_LOCAL_TASK;
  $items['admin/settings/smush-it/settings']['weight'] = -10;
  $items['admin/settings/smush-it/settings']['title'] = 'Settings';
  
  //file listing
  $items['admin/settings/smush-it/files'] = array(
    'title' => 'Files',
    'access callback' => 'user_access',
    'page callback' => '_smush_it_files',
    'access arguments' => array('administer upload'),
    'type' => MENU_LOCAL_TASK,
    'weight'=>'0',
  );
  
  //file listing
  $items['admin/settings/smush-it/stats'] = array(
    'title' => 'Stats',
    'access callback' => 'user_access',
    'page callback' => '_smush_it_stats',
    'access arguments' => array('administer upload'),
    'type' => MENU_LOCAL_TASK,
    'weight'=>'10',
  );
  
  //smush an individual image
  $items['admin/settings/smush-it/smush/%'] = array(
    'page callback' => '_smush_it_manually',
    'page arguments' => array(4),
    'access callback' => 'user_access',
    'access arguments' => array('administer upload'),
    'type'=>MENU_CALLBACK,
  );
  
  
  return $items;
}

function _smush_it_stats(){
  return t('stats page coming soon');
}


/**
 * Smush a file manually
 * @param int $file_id 
 */
function _smush_it_manually($file_id){
  $result = db_query('SELECT * FROM {files} WHERE fid = %d', $file_id);
  $file = db_fetch_array($result);
  if(_smush_image($file)){
    drupal_set_message($file['filename'] . ' has been smushed.');
  }
  drupal_goto('admin/settings/smush-it/files');
}

/**
 * Displays the images you have uploaded, lets you smush them one by one if you want to
 * @return type 
 */
function _smush_it_files() {

  $header = array(
    array(
      'data' => t('Filename'),
      'field' => 'files.filename',
      'sort' => 'asc'
    ),
    t('Path'),
    array(
      'data' => t('Mime'),
      'field' => 'files.filemime',
    ),
    array(
      'data' => t('Size'),
      'field' => 'files.filesize',
    ),
    array(
      'data' => t('Saved'),
      'field' => 'smush_it.space_saved',
    ),
    array('data' => t('Operations'), 'colspan' => '3')
  );

  $q = 'SELECT files.*, smush_it.space_saved, smush_it.smushid FROM {files}
    LEFT JOIN {smush_it} ON files.fid = smush_it.fid
    AND filemime IN (\'image/jpeg\', \'image/png\', \'image/gif\')';

  $limit = 25;

  $q .= tablesort_sql($header);

  $result = pager_query($q, $limit);

  $table_rows = array();
  while ($file = db_fetch_object($result)) {
    $row = array(
      array('data' => l($file->filename, $file->filepath)),
      array('data' => $file->filepath),
      array('data' => $file->filemime),
      array('data' => $file->filesize),
      array('data' => $file->space_saved),
    );
    //if the file has not been smushed, this will not be set, so show them a link to smush the file
    if (empty($file->smushid)) {
      $row[] = array('data' => l('smush', "admin/settings/smush-it/smush/$file->fid"));
    } else {
      $row[] = array('data' => '');
    }
    $table_rows[] = $row;
  }
  $output = '<h3>' . t('Smushed File Overview') . '</h3>';

  $tags = array(
    'first',
    '<prev',
    '',
    'next>',
    'last',
  );

  $output .= theme('table', $header, $table_rows);
  $output .= theme('pager', $tags, $limit);
  return $output;
}

/**
 * The smush.it admin settings form
 * @return array 
 */
function _smush_it_form_builder() {
  //in this example i'm creating a checkbox for each existing content type
  $form['cron_count'] = array(
    '#type' => 'textfield',
    '#title' => t('Number of images processed during cron'),
    '#description' => t('If your cron jobs are running too long, make this a smaller number.'),
    '#default_value' => variable_get('_smush_it_cron_count', 10)
  );

  $form['cron_active'] = array(
    '#type' => 'checkbox',
    '#title' => t('Process images during cron'),
    '#description' => t('If you don\'t want smush.it to run when the cron job fires, leave this un-checked.'),
    '#default_value' => variable_get('_smush_it_cron_active', false)
  );

  $form['on_create_update'] = array(
    '#type' => 'checkbox',
    '#title' => t('Smush files on create/update'),
    '#description' => t('If you want the cron job to handle smushing of images, check this off to ignore the create / update node action.'),
    '#default_value' => variable_get('_smush_it_on_create_update', false)
  );

  $form['test_mode'] = array(
    '#type' => 'checkbox',
    '#title' => t('Testing Mode'),
    '#description' => t('If you want to test things locally.'),
    '#default_value' => variable_get('_smush_it_testing', false)
  );

  $form['test_image'] = array(
    '#type' => 'textfield',
    '#title' => t('Testing Image'),
    '#description' => t('The url to an image that you want to test with. Be nice, don\'t eat somone elses bandwidth up. !!Note: Your local images will be replaced by this one.!!'),
    '#default_value' => variable_get('_smush_it_test_image', '')
  );

  $form['save'] = array(
    '#type' => 'submit',
    '#value' => t('Save'),
    '#executes_submit_callback' => true
  );

  $form['#submit'] = array(
    '_smush_it_form_submit'
  );

  return $form;
}

/**
 * Save the submitted values
 * @param type $form
 * @param type $form_state 
 */
function _smush_it_form_submit($form, &$form_state) {
  if ($form['cron_active']['#value']) {
    variable_set('_smush_it_cron_active', true);
  } else {
    variable_set('_smush_it_cron_active', false);
  }
  $cron_count_value = (int) $form['cron_count']['#value'];
  if ($cron_count_value && $cron_count_value >= 0) {
    variable_set('_smush_it_cron_count', (int) $cron_count_value);
  } elseif ($cron_count_value && $cron_count_value < 0) {
    form_set_error('', t('Cron count should be an integer >= 0.'));
  }

  if ($form['test_mode']['#value']) {
    variable_set('_smush_it_testing', true);
  } else {
    variable_set('_smush_it_testing', false);
  }

  if ($form['on_create_update']['#value']) {
    variable_set('_smush_it_on_create_update', true);
  } else {
    variable_set('_smush_it_on_create_update', false);
  }

  if ($form['test_image']['#value']) {
    variable_set('_smush_it_test_image', $form['test_image']['#value']);
  } else {
    variable_set('_smush_it_testing', '');
  }

  drupal_set_message('Smush.it settings updated', 'status');
}